### ISSUE TITLE
Flow/Operation name doesn't support foreign chars and isn't validated in verifier

### ISSUE THREAD

**Issue by einatneu** [CloudSlang/cloud-slang#140]
Flow/Operation name doesn't support foreign chars and isn't validated in verifier, for exmaple: 你好

**Comment by Bonczidai** [comment]
need to check whether it was fixed with recent encoding fixes

**Comment by Bonczidai** [comment]
after the encoding enhancement, CloudSlang runtime works perfectly if you supply UTF-8 as `cslang.encoding` var

need to do:
 - builder fails since we have no config folder - need to add config config folder similar to what we have in CLI -- and it will work (encoding in non interactive mode)
- need to investigate why CLI fails in windows (encoding in interactive mode)
