### ISSUE TITLE
Failed to compile flow which uses subflow located in file in the same folder

### ISSUE THREAD

**Issue by genadi-hp** [CloudSlang/cloud-slang#339]
Let's say we have flow flow_system_properties_subflow.sl in flow_system_properties_subflow.sl which uses simplecp.flows.flow_system_properties_subflow_level1 which located in file simplecp.flows.flow_system_properties_subflow_level1.sl located in the same folder

When executing cli with command

run --f c:/Temp/slang/tests/SimpleCp/flow_system_properties_subflow.sl --cp c:/Temp/slang/tests

We get error

Command failed java.lang.RuntimeException: java.lang.RuntimeException: Reference: 'simplecp.flows.flow_system_properties_subflow_level1' in executable: 'flow_system_properties_subflow', wasn't found in path

When executing command with specifying --cp with flow path

run --f c:/Temp/slang/tests/SimpleCp/flow_system_properties_subflow.sl --cp c:/Temp/slang/tests/SimpleCp

We get error

Command failed java.lang.RuntimeException: java.lang.IllegalArgumentException: Source flow_system_properties_subflow has dependencies but no path was given to the compiler

**Comment by oritstone** [comment]
@genadi-hp this is only a CLI bug. You should be able to run it elsewhere successfully.
The bug is actually that in the CLI compilation, we do not support as dependencies CloudSlang sources that contains in their full name the string "properties" or "inputs". 
If you change the name of the flows to not contain those strings, it should work
