### ISSUE TITLE
CLI hangs at the last step of the flow

### ISSUE THREAD

**Issue by gituser173** [CloudSlang/cloud-slang#437]
Running the flow in two separate CLI runs works:
![cli1](https://cloud.githubusercontent.com/assets/12094982/9461330/96dceb08-4b16-11e5-9aa4-d9ffe39b75f1.jpg)
 
Running the flow in one CLI run doesn’t work, it hangs at the “test_http_client_action_delete_db” step:
![cli2](https://cloud.githubusercontent.com/assets/12094982/9461334/9b57d670-4b16-11e5-81a9-13d8e79328fa.jpg)

From what I can see from the execution.log file it hangs after setting up the inputs and before executing http_client_action.
Execution log: http://pastebin.com/5LZDin7B

**Comment by meirwah** [comment]
@gituser173 did you look into this?

**Comment by Bonczidai** [comment]
the execution gets to `io.cloudslang.content.httpclient.execute.HttpClientExecutor.execute()` method which calls the apache service:

![http_call](https://cloud.githubusercontent.com/assets/8058961/9716609/0c4fcff6-5574-11e5-909c-cc3d1beba8f7.png)

so, I don't think the flow hangs because of CLI / http client implementation - the logic of the flow / docker image with http server may have a bug which causes this behavior

**Comment by Bonczidai** [comment]
@mihaitusa when you finish the *http client test*, please leave a note here, so we will be able to close this issue

**Comment by mihaitusa** [comment]
This defect can be close. I try to run in several ways the test flow (against the same docker container - RESTHeart 0.10 API) with steps in different orders or from OO. The flow hang not only at POST step but also at GET step. It seems that  RESTHeart 0.10 API docker image isn't quite stable. I rewrite the test flow to ran it against other API and despite the fact that now has more steps it doesn't hang anymore. So, the conclusion is obvious. @Bonczidai please close it.
