### ISSUE TITLE
Support backward compatibility - navigation section to list

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#600]
- all collections to list
- all strings to object
- align terminology

**Comment by Bonczidai** [comment]
IMHO

- all collections to list:
  - inputs, outputs, tasks in workflow section, results are already lists
  - **navigate section** need to be transformed to list (now it's object) -- I suggest to to do this now and enhance it in #569 
  - on_failure, aggregate section is ok

- all strings to object: if now we have `argument: value` and later we want to add modifiers like
```yaml
- argument: # object val
    default: value
    sensitive: true
```
will not break backward compatibility since everything that works now will work in future versions too (new modifiers will have default value in that case) and this syntax is nice from author POV -- I think we need **no further action here**

- backward compatibility *may* be affected by the cloudslang versioning plans (e.g. adding version tag in DSL)

- align terminology: based on feedback, `overridable` keyword is descriptive-enough -- need a better name for it
