### ISSUE TITLE
A non indicative error in CLI v.0.9.50 for parameter Directory

### ISSUE THREAD

**Issue by milanafinkel** [CloudSlang/cloud-slang#606]
Description:
Entering command into the CLI that contains a directory which doesn't exists will cause for a non indicative error.

Steps to reproduce:
1. Write a command in the CLI that contains a directory which does not exists :in this example I wrote the directories-  /content/content 
```
cslang>run --f C:/Users/finkelm/Desktop/tutorials/hiring/new_hire.sl --cp C:/Use
rs/finkelm/Desktop/tutorials,C:/Users/finkelm/Desktop/cslang# /content/content/io/
cloudslang/base --i first_name=john,last_name=doe --spf C:/Users/finkelm/Desktop
/tutorials/properties/bcompany.prop.sl
```
Actual result:
I got this error massage that didn't tell me what directory is the problematic one.

```
Command failed java.lang.IllegalArgumentException: Parameter 'directory' is not
a directory
```
Expected result:
I expect to get an error that tells me which directory the error is talking about.

**Comment by SamMarkowitz** [comment]
I was helping to debug the problem and the issue was that one of the paths used in the --cp wasn't correct.

I think the confusion was that the error message refers to a parameter 'directory', but the user has no idea what that it. There was no way to know that it referred to the value of the --cp flag. We were trying to figure out what flow/operation had something named 'directory' in it.

**Comment by Bonczidai** [comment]
did you use v0.9.50.RC1?

agree, we should display which directory is missing

**Comment by SamMarkowitz** [comment]
Yes, she was using the latest release.

**Comment by milanafinkel** [comment]
Hi, is there any news about the display of  which directory is missing?
